# Plugins that should be downloaded
# Format:
# <plugin-name>:
#   url: gh:<user/repo>:releaseFileName or <file url>
# Comment out plugins that you don't want to load by default
plugins:
  GameManager:
    url: gh:GameManagementAPI/GameManager:GameManager-1.21.11.jar

  GameLobby:
    url: gh:GameManagementAPI/GameLobby:GameLobby-1.21.11.jar

  GameStats:
    url: gh:GameManagementAPI/GameStats:GameStats-1.21.11.jar

  RankSystem:
    url: gh:Vaycore-Network/RankSystem:RankSystem-1.21.11.jar


# Language configuration
language:
  # The default language
  # used for console and players that don't have a specific language specified
  default: "english"

  # Path to file that stores player-languages
  db: "./languages.yml"

  # Path to directory where language translations will be stored
  translations-dir: "./langs/"